/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import entidades.Smartphone;
import entidades.Venta;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author taisa
 */
public class pnlVentasCompletas extends javax.swing.JPanel {

    /**
     * Creates new form pnlVentasCompletas
     */
    public pnlVentasCompletas() {
        initComponents();
        llenarTabla();
    }
    
    public void llenarTabla(){
      
        DefaultTableModel modelo = (DefaultTableModel) tblVentas.getModel();
        
        modelo.setRowCount(0);
        
        for(Venta vta : Principal.ventaImpl.getVentas()){
            int totalSmart = 0;
            String nombreSmart= "";
            
            for(Smartphone sm : vta.getSmartphones()){
                totalSmart+= sm.getStock();
                nombreSmart+= sm.getNombre()+", ";
            }
            
            modelo.addRow(new Object[]{
                vta.getFecha(),
                vta.getComprador().getNombre(),
                vta.getVendedor().getNombre(),
                totalSmart,
                nombreSmart,
                vta.getTotal(),                
                vta.isCredito() ? "SI":"NO"
            });
            
            /*
            
            String cuentaCredito = vta.isCredito() == false ? "NO" : "SI";
            String textoDeEntrada = "Soy Mayor de edad";
            int esMayor = textoDeEntrada == "Soy Menor" ? 15 : 18;
            
            IF Ternario 
            condicion ? verdadero : falso
            
            if(condicion){
                //Si es verdadero
            }else{
                //Si es falso
            }
            
            */
            
            
        }
        
        tblVentas.setModel(modelo);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVentas = new javax.swing.JTable();

        setBackground(new java.awt.Color(51, 51, 51));

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("VENTAS COMPLETADAS");

        tblVentas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Fecha", "Comprador", "Vendedor", "Total Smartphones", "Smartphones", "Total", "Credito"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblVentas.setColumnSelectionAllowed(true);
        tblVentas.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblVentas);
        tblVentas.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (tblVentas.getColumnModel().getColumnCount() > 0) {
            tblVentas.getColumnModel().getColumn(0).setResizable(false);
            tblVentas.getColumnModel().getColumn(1).setResizable(false);
            tblVentas.getColumnModel().getColumn(2).setResizable(false);
            tblVentas.getColumnModel().getColumn(3).setResizable(false);
            tblVentas.getColumnModel().getColumn(4).setResizable(false);
            tblVentas.getColumnModel().getColumn(5).setResizable(false);
            tblVentas.getColumnModel().getColumn(6).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 692, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 496, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVentas;
    // End of variables declaration//GEN-END:variables
}
