/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import controlador.VentasImpl;
import javax.swing.ImageIcon;


/**
 *
 * @author taisa
 */
public class Principal extends javax.swing.JFrame {

    public static VentasImpl ventaImpl = new VentasImpl();

    pnlVenta pnlVenta = new pnlVenta();
    pnlSmartphone pnlSmartphone = new pnlSmartphone();
    pnlPersona pnlPersona = new pnlPersona();
    pnlVentasCompletas pnlVentasCompletas = new pnlVentasCompletas();
    
    
    public Principal() {        
        //Se obtiene la imagen del icono a traves de un ImageIcon
        ImageIcon icono = new ImageIcon(getClass().getResource("/vistas/imagenes/telefono-inteligente.png"));
        //Se obtiene la imagen desde el icono para aplicarla al formulario.
        setIconImage(icono.getImage());
        
        initComponents();
        pnlVenta.setVisible(true);
        pnlSmartphone.setVisible(false);    
        pnlPersona.setVisible(false);
        pnlVentasCompletas.setVisible(false);
        panelPrincipal.add(pnlVenta);
        
    }
    
    private void cambiarPanel(int op){
        java.awt.Color colorSelec =   new java.awt.Color(0, 102, 102);
        //Ponemos todos los paneles visible false        
        pnlVenta.setVisible(false);
        pnlSmartphone.setVisible(false);
        pnlPersona.setVisible(false);
        pnlVentasCompletas.setVisible(false);
        
        //Asignamos color
        lblSmartphone.setBackground(colorSelec);
        lblPersonas.setBackground(colorSelec);
        lblVentasCompletas.setBackground(colorSelec);
        
        //Quitamos el opaco
        lblVentas.setOpaque(false);
        lblSmartphone.setOpaque(false);
        lblPersonas.setOpaque(false);
        lblVentasCompletas.setOpaque(false);
        
        panelPrincipal.remove(1);//0 Es el menu y el 1 el panel activo
        
        switch(op){
            case 1:  //Venta
                lblVentas.setOpaque(true);
                pnlVenta.setVisible(true);
                pnlVenta.llenarCombos();
                pnlVenta.llenarTabla();
                panelPrincipal.add(pnlVenta);
                break; 
            case 2:  //Smartphone
                lblSmartphone.setOpaque(true);
                pnlSmartphone.setVisible(true);
                panelPrincipal.add(pnlSmartphone);
                break;    
            case 3:  //Personas
                lblPersonas.setOpaque(true);                
                pnlPersona.setVisible(true);
                panelPrincipal.add(pnlPersona);
                break;  
            case 4:  //Ventas completadas
                lblVentasCompletas.setOpaque(true);
                pnlVentasCompletas.setVisible(true);
                pnlVentasCompletas.llenarTabla();
                panelPrincipal.add(pnlVentasCompletas);
                break;     
        }
        
        this.revalidate();
        this.repaint();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelPrincipal = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lblVentas = new javax.swing.JLabel();
        lblSmartphone = new javax.swing.JLabel();
        lblPersonas = new javax.swing.JLabel();
        lblVentasCompletas = new javax.swing.JLabel();
        lblSalir = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Venta de Smartphones");

        panelPrincipal.setBackground(new java.awt.Color(51, 51, 51));
        panelPrincipal.setLayout(new java.awt.BorderLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new java.awt.GridLayout(8, 1));

        lblVentas.setBackground(new java.awt.Color(0, 102, 102));
        lblVentas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVentas.setForeground(new java.awt.Color(255, 255, 255));
        lblVentas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/bolsa-de-la-compra.png"))); // NOI18N
        lblVentas.setText("Venta");
        lblVentas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVentas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVentas.setOpaque(true);
        lblVentas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblVentas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentasMouseClicked(evt);
            }
        });
        jPanel2.add(lblVentas);

        lblSmartphone.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSmartphone.setForeground(new java.awt.Color(255, 255, 255));
        lblSmartphone.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSmartphone.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/telefono-inteligente.png"))); // NOI18N
        lblSmartphone.setText("Smartphone");
        lblSmartphone.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSmartphone.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSmartphone.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSmartphone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSmartphoneMouseClicked(evt);
            }
        });
        jPanel2.add(lblSmartphone);

        lblPersonas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblPersonas.setForeground(new java.awt.Color(255, 255, 255));
        lblPersonas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblPersonas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/man.png"))); // NOI18N
        lblPersonas.setText("Personas");
        lblPersonas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblPersonas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblPersonas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblPersonas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblPersonasMouseClicked(evt);
            }
        });
        jPanel2.add(lblPersonas);

        lblVentasCompletas.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblVentasCompletas.setForeground(new java.awt.Color(255, 255, 255));
        lblVentasCompletas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVentasCompletas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/negocios-y-finanzas.png"))); // NOI18N
        lblVentasCompletas.setText("Ventas");
        lblVentasCompletas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVentasCompletas.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblVentasCompletas.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblVentasCompletas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVentasCompletasMouseClicked(evt);
            }
        });
        jPanel2.add(lblVentasCompletas);

        lblSalir.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lblSalir.setForeground(new java.awt.Color(255, 255, 255));
        lblSalir.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/power-off.png"))); // NOI18N
        lblSalir.setText("Salir");
        lblSalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblSalir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSalir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalirMouseClicked(evt);
            }
        });
        jPanel2.add(lblSalir);

        panelPrincipal.add(jPanel2, java.awt.BorderLayout.LINE_START);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 884, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, 585, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblSalirMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalirMouseClicked
        System.exit(0);
    }//GEN-LAST:event_lblSalirMouseClicked

    private void lblVentasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasMouseClicked
        cambiarPanel(1);
    }//GEN-LAST:event_lblVentasMouseClicked

    private void lblSmartphoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSmartphoneMouseClicked
       cambiarPanel(2);
    }//GEN-LAST:event_lblSmartphoneMouseClicked

    private void lblPersonasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblPersonasMouseClicked
        cambiarPanel(3);
    }//GEN-LAST:event_lblPersonasMouseClicked

    private void lblVentasCompletasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVentasCompletasMouseClicked
        cambiarPanel(4);
    }//GEN-LAST:event_lblVentasCompletasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblPersonas;
    private javax.swing.JLabel lblSalir;
    private javax.swing.JLabel lblSmartphone;
    private javax.swing.JLabel lblVentas;
    private javax.swing.JLabel lblVentasCompletas;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
